- README.md
- package-lock.json
- package.json
- src/__tests__/definitions/invalid-json-path.json
- src/__tests__/validator.test.js
- src/validator.js
> JSON path validation

- package-lock.json
- package.json
- src/schemas/choice.json
- src/schemas/fail.json
- src/schemas/parallel.json
- src/schemas/pass.json
- src/schemas/task.json
- src/schemas/wait.json
- src/validator.js
> allow null values for all paths

- package-lock.json
- package.json
- src/__tests__/definitions/invalid-error-equals.json
- src/schemas/parallel.json
- src/schemas/task.json
> #21 catch error equals

- package-lock.json
- package.json
- src/__tests__/definitions/valid-parallel-with-result-path.json
- src/schemas/parallel.json
> adding ResultPath in Parallel state

- package-lock.json
- package.json
- src/__tests__/definitions/invalid-inexistant-state.json
- src/lib/missing-transition-target.js
- src/validator.js
> 20 state exists

- package-lock.json
- package.json
- src/__tests__/definitions/valid-parallel-with-retry.json
- src/schemas/parallel.json
Retry can be available on Parallel state: https://states-language.net/spec.html#state-type-table
Fixes #27
> adding Retry to Parallel state

- package-lock.json
- package.json
- src/__tests__/definitions/valid-task-batch.json
- src/schemas/task.json
Recent step function update introduces the following "magic arns".
- DynamoDB `arn:aws:states:::dynamodb:getItem` https://docs.aws.amazon.com/step-functions/latest/dg/connectors-ddb.html
- Batch `arn:aws:states:::batch:submitJob.sync` https://docs.aws.amazon.com/step-functions/latest/dg/connectors-batch.html
This PR makes `Resource` accept magic arns.
> Make task resource accept magic arns

- src/__tests__/definitions/invalid-map-missing-iterator.json
- src/__tests__/definitions/valid-map-with-catch.json
- src/__tests__/definitions/valid-map-with-parameters.json
- src/__tests__/definitions/valid-map-with-retry.json
- src/__tests__/definitions/valid-map.json
- src/schemas/map.json
- src/schemas/state.json
- src/validator.js
official documentation [here](https://docs.aws.amazon.com/step-functions/latest/dg/amazon-states-language-map-state.html)
> feat: support the Map state

- package-lock.json
- package.json
- src/__tests__/definitions/invalid-parallel-branch-type.json
- src/schemas/parallel.json
> Definition of Branch is incorrect

- src/schemas/choice.json
- src/schemas/parallel.json
- src/schemas/task.json
> support new features

- package-lock.json
- package.json
- src/validator.js
> fix error displaying

- package-lock.json
- package.json
- src/__tests__/definitions/valid-context.json
- src/lib/json-path-errors.js
> Support object context

- package-lock.json
- package.json
- src/__tests__/definitions/valid-parameters-array.json
- src/__tests__/definitions/valid-parameters-object.json
- src/schemas/map.json
- src/schemas/parallel.json
- src/schemas/pass.json
- src/schemas/task.json
> Allowing array and object in Parameters

- src/__tests__/definitions/invalid-cfn-definition-substitutions.json
- src/__tests__/definitions/valid-cfn-definition-substitutions.json
- src/schemas/task.json
Related Issue: https://github.com/ChristopheBougere/asl-validator/issues/54
> Added support for CFN definitionSubstitutions

- package-lock.json
- package.json
- src/__tests__/definitions/invalid-state-name-too-long.json
- src/schemas/state-machine.json
> State name length

- package-lock.json
- package.json
Fixes #72 
There are breaking changes in new versions of commander
> Rollback commander version

- src/schemas/choice.json
- src/schemas/errors.json
- src/schemas/fail.json
- src/schemas/map.json
- src/schemas/parallel.json
- src/schemas/pass.json
- src/schemas/state-machine.json
- src/schemas/state.json
- src/schemas/succeed.json
- src/schemas/task.json
- src/schemas/wait.json
- src/validator.js
These changes will allow editors like VSCode to reference the schema through a URL and enable auto-completion and validation.
> support schema validation in IDEs such as VSCode

- .gitignore
- src/__tests__/definitions/invalid-map-ob-link.json
- src/__tests__/definitions/invalid-parallel-ob-link.json
- src/lib/state-transitions.js
- src/validator.js
> fix: detect invalid outbound transition from map/parallel state.

- src/__tests__/definitions/invalid-missing-terminal-map.json
- src/__tests__/definitions/invalid-missing-terminal-parallel.json
- src/__tests__/definitions/invalid-missing-terminal.json
- src/lib/terminals.js
- src/validator.js
> add rule to check for missing terminal

- src/__tests__/definitions/valid-map-nested.json
- src/lib/state-transitions.js
> fix: bad jsonpath in nextAndDefaultTargets function

- package-lock.json
- package.json
- src/__tests__/definitions/valid-fail.json
- src/__tests__/definitions/valid-parallel-nested.json
- src/__tests__/definitions/valid-path-with-hypen.json
- src/lib/json-path-errors.js
- src/lib/missing-transition-target.js
- src/lib/state-names.js
- src/lib/state-transitions.js
- src/lib/terminals.js
This fixes #81 and perhaps the browser issue #77 
includes a couple of unrelated test files for better coverage
> migrate to Jsonpathplus to better match the ASL spec

- src/__tests__/definitions/invalid-dupe-fields.asl.json
- src/checks/duplicate-payload-template-fields.ts
- src/types.ts
- src/validator.ts
> feat: detect duplicate fields in payload templates post eval

- package-lock.json
- src/__tests__/definitions/invalid-payload-template.asl.json
- src/__tests__/error-reporting.test.ts
- src/checks/json-schema-errors.ts
> test: add case with bad parameters to assert on error message

- package-lock.json
- package.json
- src/__tests__/definitions/valid-pass-negativeIndex.json
the grammar was missing support for negative offsets. I added more tests there. This PR includes a test to show it working with v0.10.0
> fix: upgrade path lib and added test to show it working

- src/__tests__/definitions/valid-pass-array.json
- src/__tests__/error-reporting.test.ts
- src/schemas/paths.json
> fix(schemas): payload template definition was too restrictive

- src/__tests__/definitions/valid-parallel-nested-2.json
- src/checks/state-transitions-errors.ts
Bringing [this v2 fix](https://github.com/ChristopheBougere/asl-validator/pull/100) to v3
> fix: fix bug in JSONPath traversal to nested parallel states giving false positive (#100)

- src/__tests__/definitions/invalid-duplicate-fields-nested.json
- src/__tests__/definitions/invalid-duplicate-fields.json
- src/checks/duplicate-payload-template-fields.ts
> fix(check): replace jsonpath-plus expression with traversal for dupe fields

- package-lock.json
- package.json
- src/__tests__/definitions/valid-intrinsic-functions.asl.json
> update path parser lib and add test with all intrinsic functions

- src/__tests__/definitions/invalid-wait-duration.json
- src/checks/exactlyOneOfProperty.ts
- src/checks/get-states.ts
- src/checks/terminalStateWithNext.ts
- src/checks/waitDuration.ts
- src/types.ts
- src/validator.ts
refactor: leverage common code between exclusive prop checks
> feat: added check for wait duration properties

- src/__tests__/error-reporting.test.ts
- src/checks/mapChecks.ts
- src/schemas/map.json
- src/types.ts
- src/validator.ts
feat: add check for map with parameters and itemselector
> refactor: replace map one of with checker

- src/__tests__/definitions/invalid-map-tolerated-value.json
- src/__tests__/definitions/invalid-map-tolerated.json
- src/__tests__/definitions/valid-map-tolerated.json
- src/schemas/map.json
- src/types.ts
- src/validator.ts
Easy change to add the new properties to the Map schema and update the state checker logic
> fix: added missing properties to map

- README.md
Seems like the empty commit didn't trigger a new release in #157
> Force new release

- package-lock.json
- package.json
> feat: update asl-path-validator to mitigate another jsonpath-plus CVE
