src/__tests__/definitions/invalid-task-alias-function.json
src/__tests__/definitions/valid-task-alias-function.json
src/schemas/task.json

You can specify a specific alias of a function from a step function to
enable the pinning of step function versions to specific versions of
Lambdas. This change adds this syntax to the task ARN regex.
Fixes #38
I've tested this change with the project that exhibited the issue in the first place and it seems to be working well. Let me know if you can think of a test case I've missed.

Fix validation of lambda aliases in task ARNs

---

src/__tests__/definitions/valid-pass-state.json
src/schemas/pass.json

See [issue 40](https://github.com/airware/asl-validator/issues/40) for context.
@ChristopheBougere - Let me know if I'm interpreted your comment on the issue incorrectly - but I think I made the necessary changes. Let me know if there are any questions or concerns about my proposed changes.
Note: My `valid-pass-state.json` file is just a simplied version of this [sample project](https://docs.aws.amazon.com/step-functions/latest/dg/sample-project-transfer-data-sqs.html#sample-sqs-code-examples)

fixing pass state to have parameters property

---

package-lock.json
package.json
src/__tests__/definitions/invalid-error-equals-type.json
src/schemas/map.json
src/schemas/parallel.json
src/schemas/task.json

Here is the syntax for declaring `string[]` in json schema: https://json-schema.org/understanding-json-schema/reference/array.html
The current definitions before this change would produce a schema that was an array of objects. `{ [key: string]: any }[]` when used with the https://github.com/bcherny/json-schema-to-typescript package
The current schemas dont seem to be used in the repo anywhere, and definitely not in the tests, so this wouldnt have been caught here. However the downstream package [asl-types](https://www.npmjs.com/package/asl-types) does depend on these schemas, which is where i saw this issue.
I have validated in that package that changing `items` -> `item` did in fact fix the conversion process.
Here is the issue created in that package …

fix(error-equals): update error equals schemas to have the correct syntax

---

src/validator.js

Missing transition target errors set the properties "Error code" and "Message". The existing formatting logic is based on "Code" and "Message" and will fallback to "message" which isn't set with missing transition target errors, resulting in no error text. This fixes that.
Note: I couldn't find anywhere where "Code" was being used but just to be safe I had it check for both rather than to ONLY look for "Error code".

Fix bug to show missing transition target errors

---

package-lock.json
src/__tests__/definitions/valid-path-array-context.json
src/lib/json-path-errors.js

the update to jsonpath-plus library changed to evaluate the expressions against the definition in lieu of having an exposed compile function
maybe I'm missing where parse/compile is exposed in JSONPath
for now, if the first call fails, we'll try it again w/ a non-empty array
closes #90

feat: work around for JSONPath regression

---

src/__tests__/definitions/valid-parameters-issue104.json
src/__tests__/error-reporting.test.ts
src/checks/duplicate-payload-template-fields.ts
src/checks/json-schema-errors.ts
src/schemas/paths.json

AJV is failing the input schema since it is matching on two of the available types in its `oneOf` definition. 
closes #104 
fix(schemas): recursive def fixed where oneOf options intersected on array types
fix(check): catch jsonpath error in duplicate-payload-template-fields.ts
refactor(check): decode URI encoded values for cleaner error reporting

fix schema definition for payload template to avoid the oneOf options intersecting

---

src/__tests__/definitions/valid-null-input.json
src/__tests__/definitions/valid-null-result.json
src/schemas/paths.json

Closes #106. Treats a ResultPath of `null` as valid schema. New to the refactored version here so please offer corrections where needed.

fix: null is a valid resultpath

---

src/__tests__/definitions/invalid-choice-state.json
src/__tests__/definitions/valid-choice-state.json
src/schemas/choice.json

As described in the [AWS Choice step documentation](https://docs.aws.amazon.com/step-functions/latest/dg/amazon-states-language-choice-state.html)
> Choice states don't support the End field. In addition, they use Next only inside their Choices field.

fix: choice statements must have a Next in first level operators

---

src/__tests__/definitions/valid-null-parameter.json
src/__tests__/definitions/valid-null-resultSelector.json
src/checks/duplicate-payload-template-fields.ts

When a `Parameters`/`ResultSelector` block has a `null` value somewhere inside it's identified as an object and so gets checked, resulting in a `TypeError`
Example error before the fix:
```
TypeError: Cannot convert undefined or null to object
at Function.keys (<anonymous>)
17 |     const inspectKeys = (parent: Record<string, unknown>): void => {
18 |         const keys: Record<string, number> = {};
> 19 |         Object.keys(parent).forEach((key) => {
|                ^
20 |             const keyPostEval = key.endsWith(".$") ? key.substring(0, key.length - 2) : key;
21 |             const current = keys[keyPostEval];
22 |             if (current) {
```

Handle null values in `Parameters` and `ResultSelector`

---

src/__tests__/definitions/invalid-next-with-end.json
src/checks/get-states.ts
src/checks/missing-terminal-state-errors.ts
src/checks/terminalStateWithNext.ts
src/schemas/map.json
src/schemas/parallel.json
src/schemas/pass.json
src/schemas/task.json
src/schemas/wait.json
src/types.ts
src/validator.ts

See the discussion #119 
This replaces the JSON rules for `Next` and `End` with a typescript function. The purpose is to improve the error messages and set a pattern for a few other mutually exclusive properties. The new ones for `Map` plus existing ones like TimeSeconds and TimeSecondsPath.

refactor: use checker for next end validation instead of schema rule

---

src/schemas/paths.json

Small PR to remove an unused definition from the schema. This was spotted in a recent issue a few weeks back.

chore: remove unused definition in paths

---

src/__tests__/definitions/valid-map-noconfig.asl.json
src/schemas/map.json

This closes #135 
I added a test to recreate the failure and then modified the map's schema. The previous definition looked ok but evidently resulted in the field being required.
This change moves the `oneOf` into the ProcessorConfig definition (still not a required field). The options for the `oneOf` enumerate the two valid configs defined by AWS

fix: semantics for item processor

---

src/__tests__/definitions/invalid-choice-state-variable.json
src/schemas/choice.json

This was a miss when I added the validation for the path expressions. 
From the [spec](https://docs.aws.amazon.com/step-functions/latest/dg/amazon-states-language-choice-state.html) for the Choice state: 
>The values of Variable and Path fields in a comparison must be valid [Reference Paths](https://docs.aws.amazon.com/step-functions/latest/dg/amazon-states-language-paths.html#amazon-states-language-reference-paths).
Small change to update the schema and provide a test for the negative case.
closes #144

fix: set choice state variable and path fields set to reference paths

---

src/__tests__/definitions/invalid-fail-dupe-cause.json
src/__tests__/definitions/invalid-fail-dupe-error.json
src/__tests__/definitions/valid-fail-paths.json
src/schemas/fail.json
src/types.ts
src/validator.ts

This is a partial fix for the issue. I added support for the two new fields but typed them as a `string` since the existing validators for the ASL paths don't support the custom logic needed to accept a Reference Path and subset of Intrinsic Functions
This at least unblocks the use of the fields.

fix: support path fields on fail for cause and error

---

package-lock.json
package.json
src/__tests__/definitions/valid-current-value-predicate.json

closes #150 
The expression validator didn't support the construct of a predicate with the current value operator (`@`). I fixed this in that repo and I'm bumping the version here to use the latest. 
Here's the relevant part of the grammar that changed:
https://github.com/massfords/asl-path-validator/blob/main/src/aslPaths.pegjs#L89-L102
Note the addition of the new rule `predicate` which allows for the current value operator to be used in a comparison expression
It's also worth noting that AWS has since made reference to the official JSONPath specification in their docs which has its own grammar so adopting that grammar in place of my peg solution is something to look at when there's time

fix: bump version of path validator to support current value expr

---

package-lock.json
package.json

chore: bump version on jsonpath-plus
chore: bump version on asl-path-validator

bump dependency to address vulnerability in jsonpath-plus library

---

package-lock.json
package.json
src/__tests__/definitions/invalid-jsonata-fields.json
src/__tests__/definitions/invalid-jsonata-path-fields.asl.json
src/__tests__/definitions/invalid-variable-result-path.json
src/__tests__/definitions/valid-jsonata.asl.json
src/checks/json-schema-errors.ts
src/checks/state-checks.ts
src/schemas/choice.json
src/schemas/fail.json
src/schemas/jsonata.json
src/schemas/map.json
src/schemas/parallel.json
src/schemas/pass.json
src/schemas/paths.json
src/schemas/state-machine.json
src/schemas/succeed.json
src/schemas/task.json
src/schemas/wait.json
src/types.ts
src/validator.ts

chore: bump asl-path-validator version
chore: npm audit fix
closes: #161 
This is the minimum to support the new variables fields
- add QueryLanguage field to root state machine
- add QueryLanguage field to states
- add new JSONata specific fields
- add some checks for invalid use of JSONPath fields with JSONata query language and vice versa

feat: support new fields for variables

---

package-lock.json
package.json

This bumps jsonpath-plus to ^10.2.0. This should address the [RCE vulnerability in JSONPath Plus](https://github.com/advisories/GHSA-pppg-cpfq-h7wr). This has already been addressed in the [asl-path-validator](https://github.com/massfords/asl-path-validator/blob/main/package.json#L53) dependency, which also has depends on jsonpath-plus.

chore: bump jsonpath-plus to 10.2.0

---

src/schemas/choice.json

According to [AWS](https://docs.aws.amazon.com/step-functions/latest/dg/workflow-variables.html#conceptual-overview-of-variables), `Choice` state also supports `Assign`:
> The following state types support Assign to declare and assign values to variables: Pass, Task, Map, Parallel, Choice, Wait.
I can use `Assign` in the default choice and in each choice in their editor:

feat: add assign support for choice state

---

src/__tests__/definitions/invalid-map-items.asl.json
src/__tests__/definitions/valid-map-items.asl.json
src/__tests__/definitions/valid-wait-jsonata.asl.json
src/schemas/map.json
src/schemas/wait.json
src/types.ts
src/validator.ts

additional updates to schema definitions to support jsonata language
